window.DUKHUBUSTERS_CONFIG = {
  supabaseUrl: "https://bjlykfxfminmjfgilowj.supabase.co",
  supabaseAnonKey: "sb_publishable_JyUVYzb2vZoQiyLSasTNYg_P-LoaJrx",
  backendMode: "firebase",
  staticDataVersion: "20260607-static-data",
  firebaseDefaultReadLimit: 100,
  firebaseMaximumReadLimit: 300,
  firebaseConfig: {
    apiKey: "AIzaSyB1Nvaz_Vmz201izN0vwx3mK9hDbLwDB4A",
    authDomain: "dukhubusters.firebaseapp.com",
    projectId: "dukhubusters",
    appId: "1:112478053097:web:1c62da1fd66481a92f4678",
  },
  r2UploadEndpoint: "/api/r2-upload",
  r2PublicBaseUrl: "",
  buildTable: "builds",
  reportTable: "monster_reports",
  visitorTable: "site_visitors",
  dailyVisitorTable: "daily_visitors",
  guideTable: "guide_posts",
  guideBucket: "guide-media",
  guideShareUrl: "https://bjlykfxfminmjfgilowj.supabase.co/functions/v1/guide-share",
  canonicalSiteUrl: "https://busters.kr",
  profileTable: "user_profiles",
  adminEmails: ["wplife0621@gmail.com"],
};
