window.DUKHUBUSTERS_CONFIG = {
  supabaseUrl: "https://bjlykfxfminmjfgilowj.supabase.co",
  supabaseAnonKey: "sb_publishable_JyUVYzb2vZoQiyLSasTNYg_P-LoaJrx",
  backendMode: "supabase",
  firebaseConfig: {
    apiKey: "",
    authDomain: "",
    projectId: "",
    appId: "",
  },
  r2UploadEndpoint: "/api/r2-upload",
  r2PublicBaseUrl: "",
  buildTable: "builds",
  reportTable: "monster_reports",
  visitorTable: "site_visitors",
  dailyVisitorTable: "daily_visitors",
  guideTable: "guide_posts",
  guideBucket: "guide-media",
  guideShareUrl: "https://bjlykfxfminmjfgilowj.supabase.co/functions/v1/guide-share",
  canonicalSiteUrl: "https://busters.kr",
  profileTable: "user_profiles",
  adminEmails: ["wplife0621@gmail.com"],
};
